import NavBar from '../nav-footter/NavBar'
import Footer from '@/nav-footter/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClientProvider } from '@/Golobal-Redux/ClientProvider'
import NavbarMoil from '../nav-footter/NavbarMobil'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Acame Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ClientProvider >
        <NavBar/>
        <main className='bg-gray-100' style={{ paddingTop: '-4%'}}>{children}</main>
        <Footer/>
        </ClientProvider>
        </body>
    </html>
  )
}
